2024-02-26 14:28:34.160 [info] 실험 'pythonaa'이(가) 활성 상태입니다.
2024-02-26 14:28:34.160 [info] 실험 'pythonRecommendTensorboardExt'이(가) 활성 상태입니다.
2024-02-26 14:28:34.160 [info] 실험 'pythonREPLSmartSend'이(가) 활성 상태입니다.
2024-02-26 14:28:34.161 [info] 실험 'pythonTerminalEnvVarActivation'이(가) 활성 상태입니다.
2024-02-26 14:28:34.161 [info] 실험 'pythonTestAdapter'이(가) 활성 상태입니다.
2024-02-26 14:28:34.161 [info] Default formatter is set to null for workspace /root
2024-02-26 14:28:34.161 [info] Test server listening.
2024-02-26 14:28:34.186 [info] > C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -I ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-02-26 14:28:34.191 [error] [Error: Command failed: C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -I /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
/bin/sh: 1: C:UsersAdministratorAppDataLocalProgramsPythonPython310python.exe: not found

	at ChildProcess.exithandler (node:child_process:420:12)
	at ChildProcess.emit (node:events:526:35)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:514:28)
	at Pipe.<anonymous> (node:net:323:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -I /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py'
}
2024-02-26 14:28:36.206 [info] > C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -I ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
2024-02-26 14:28:36.208 [error] [Error: Command failed: C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -I /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
/bin/sh: 1: C:UsersAdministratorAppDataLocalProgramsPythonPython310python.exe: not found

	at ChildProcess.exithandler (node:child_process:420:12)
	at ChildProcess.emit (node:events:526:35)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:514:28)
	at Pipe.<anonymous> (node:net:323:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -I /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py'
}
2024-02-26 14:28:36.228 [info] > C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -c "import sys;print(sys.executable)"
2024-02-26 14:28:36.231 [error] [Error: Command failed: C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -c "import sys;print(sys.executable)"
/bin/sh: 1: C:UsersAdministratorAppDataLocalProgramsPythonPython310python.exe: not found

	at ChildProcess.exithandler (node:child_process:420:12)
	at ChildProcess.emit (node:events:526:35)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:514:28)
	at Pipe.<anonymous> (node:net:323:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -c "import sys;print(sys.executable)"'
}
2024-02-26 14:28:37.717 [info] Pylance 언어 서버를 시작하는 중입니다.
2024-02-26 15:35:30.166 [info] > conda info --json
2024-02-26 15:35:30.184 [info] Found: /usr/bin/python --> /usr/bin/python2.7
2024-02-26 15:35:30.196 [info] Found: /usr/bin/python2 --> /usr/bin/python2.7
2024-02-26 15:35:30.197 [info] Found: /usr/bin/python2.7 --> /usr/bin/python2.7
2024-02-26 15:35:30.198 [info] Found: /usr/bin/python3 --> /usr/bin/python3.7
2024-02-26 15:35:30.199 [info] Found: /usr/bin/python3.7 --> /usr/bin/python3.7
2024-02-26 15:35:30.245 [info] > /usr/bin/python -I ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
2024-02-26 15:35:30.253 [warning] [Error: Command failed: /usr/bin/python -I /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /usr/bin/python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

	at ChildProcess.exithandler (node:child_process:420:12)
	at ChildProcess.emit (node:events:526:35)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:514:28)
	at Pipe.<anonymous> (node:net:323:12)] {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/usr/bin/python -I /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py'
}
2024-02-26 15:35:30.253 [error] Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
2024-02-26 15:35:30.264 [info] > /usr/bin/python ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
2024-02-26 15:35:30.287 [info] > /usr/bin/python3 -I ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
2024-02-26 15:36:03.109 [info] Discover tests for workspace name: root - uri: /root
2024-02-26 15:36:03.110 [info] Python 인터프리터 경로: /usr/bin/python3
2024-02-26 15:36:11.272 [info] Discover tests for workspace name: root - uri: /root
2024-02-26 15:36:11.273 [info] Python 인터프리터 경로: /usr/bin/python
2024-02-26 15:36:55.578 [info] Discover tests for workspace name: root - uri: /root
2024-02-26 15:36:55.578 [info] Python 인터프리터 경로: /usr/bin/python3
2024-02-26 15:37:19.103 [info] Discover tests for workspace name: root - uri: /root/venvs/karios/app.py
2024-02-26 15:39:39.762 [info] > ./venvs/karios/bin/python -I ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
2024-02-26 15:39:39.807 [info] Discover tests for workspace name: root - uri: /root
2024-02-26 15:39:39.807 [info] Python 인터프리터 경로: ./venvs/karios/bin/python
2024-02-26 15:39:39.845 [info] > . ./venvs/karios/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/printEnvVariables.py
2024-02-26 15:39:39.845 [info] shell: bash
2024-02-26 15:39:39.892 [info] > /usr/bin/python ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/printEnvVariables.py
2024-02-26 15:39:39.892 [info] shell: bash
2024-02-26 15:39:39.913 [info] Send text to terminal: /usr/bin/python /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/printEnvVariablesToFile.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/deactivate/bash/envVars.txt
2024-02-26 15:40:09.915 [error] Failed to initialize deactivate script /bin/bash [Error: "/root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/deactivate/bash/envVars.txt" file not created
	at Timeout.<anonymous> (/root/.vscode-server/extensions/ms-python.python-2024.0.1/out/client/extension.js:2:276484)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)]
2024-02-26 15:48:21.706 [info] Send text to terminal: /root/venvs/karios/bin/python /root/venvs/karios/app.py
2024-02-26 15:48:21.758 [info] CreateEnv Trigger - Skipping for /root/venvs/karios/app.py
2024-02-26 15:51:40.805 [info] Discover tests for workspace name: root - uri: /root/venvs/karios/app.py
